FROM node:20-alpine AS compiler
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --only=production
COPY --from=compiler /app/dist ./dist

CMD ["node", "dist/workers/analysis.worker.js"]
